version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6-jessie-browsers
      - image: library/elasticsearch:5.6
    steps:
      - checkout
      - restore_cache:
          key: chahub-{{ .Branch }}-{{ checksum "requirements.dev.txt" }}
      - run: sudo pip install -r requirements.dev.txt
      - run: python manage.py collectstatic --no-input
      - save_cache:
          key: codalab-{{ .Branch }}-{{ checksum "requirements.dev.txt" }}
          paths:
          - ~/.cache/pip
      - run: py.test
      - run: flake8 src/ --ignore E501
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
