version: 2
jobs:
  test:
    docker:
        - image: circleci/python:3.6-jessie-browsers
        - image: library/elasticsearch:5.6
    steps:
        - checkout
#        - restore_cache:
#            key: chahub-{{ .Branch }}-{{ checksum "requirements.dev.txt" }}
        - run: sudo pip install -r requirements.dev.txt
        - run: python manage.py collectstatic --no-input
        - run: mkdir test-reports/
        - run:
            name: Download Selenium
            command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
        - run:
            name: Start Selenium
            command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
            background: true
        - save_cache:
            key: codalab-{{ .Branch }}-{{ checksum "requirements.dev.txt" }}
            paths:
            - ~/.cache/pip
        - run: py.test
        - run: flake8 src/ --ignore E501
 #      - run: if [[ `grep -rnw src -e 'TODO'` ]]; then (exit -1); fi
 #      - run [[ `grep -rnw src/templates/ -e 'style='` ]]; then (exit -1); fi
 #      - run [[ `grep -rnw src/static/riot -e 'style='` ]]; then (exit -1); fi

workflows:
  version: 2
  build_and_test:
    jobs:
        - test
