# Generated by Django 2.0 on 2018-07-02 19:03

from django.db import migrations, models
import utils.data


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0028_auto_20180613_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='logo_file',
            field=models.ImageField(blank=True, upload_to=utils.data.PathWrapper('competition_logos')),
        ),
    ]
